apiVersion: apps/v1
kind: Deployment
metadata:
  name: t1
  labels:
    app: t1
spec:
  selector:
    matchLabels:
      app: t1
  template:
    metadata:
      labels:
        app: t1
    spec:
      containers:
        - name: t1
          image: t1-image
          envFrom:
          - configMapRef:
              name: env-config
          ports:
            - containerPort: 5678  # for debugger
            - containerPort: 9000  # for app
